### PR TITLE
Use object code for Template Haskell

### LINKED ISSUE #107: Warnings emitted by the desugarer are not shown
I sometimes have some enabled warnings which don‘t get displayed even if all other warnings are and there are no errors in the code. A cabal run on the same file shows the warning. My feeling is it depends on the category of the warning. I noticed the problem with following categories:

* `all-missed-specialisations`
* `incomplete-patterns`

There might be more. I’d like to know if this warnings work for anybody else.

### LINKED ISSUE #614: interface-file errors when using Template Haskell since ghcide 0.2.0
I have a project that compiles with cabal and often works without a problem with ghcide.
But sometimes I see issues like this:

```
 [typecheck] [E] • Can't find interface-file declaration for data constructor SortPosition
    Probable cause: bug in .hi-boot file, or inconsistent .hi file
    Use -ddump-if-trace to get an idea of which file caused the error
```

I have seen this at different positions in my code, but sadly, also because of the heisenbugishness of this bug, I couldn‘t construct a minimal failing example yet.

This issue didn‘t happen on ghcide 0.1.0.

On thing of note: I have only met this issue on data constructors that where called like the Type they inhabit. Renaming the Type fixed the problem for me. But that might just have been luck.

**EDIT:** The Type is generated via Template Haskell.

### PR DESCRIPTION
**Pull request by wz1000**
Rework of https://github.com/mpickering/ghcide/pull/43/

Should improve performance and also functions as a workaround for #614 

We now generate object code along with the interface file. Object code is only generated for a module if

1) The module uses TH
2) Any parents of the module use TH

For this to work, we require the complete module graph. Earlier, tests were failing because `TargetFile`'s were not included in the set of known files. I fixed this, but now tests are failing because the modules don't define a `main` function. Any idea why this is happening @pepeiborra? See my last commit.

FIxes #614 
Fixes #107

### CODE REVIEW

**Comment by wz1000** [comment]
OK, I figured out the issue (`LinkBinary` triggers that, `LinkInMemory` fixes it). Not sure about the performance impact of this change...

**Comment by wz1000** [comment]
ghc-lib :(

I have no idea how to locally build this configuration, and worse still, no tests run so I have no way to know if my changes work.

File: session-loader/Development/IDE/Session.hs [hunk 1]
```diff
@@ -118,9 +118,12 @@ loadSession dir = do
         -- files in the project so that `knownFiles` can learn about them and
         -- we can generate a complete module graph
     let extendKnownTargets newTargets = do
-          knownTargets <- forM newTargets $ \TargetDetails{..} -> do
-            found <- filterM (IO.doesFileExist . fromNormalizedFilePath) targetLocations
-            return (targetTarget, found)
+          knownTargets <- forM newTargets $ \TargetDetails{..} ->
+            case targetTarget of
+              TargetFile f -> pure (targetTarget, [f])
```
Comment (wz1000) [inline session-loader/Development/IDE/Session.hs:123]: Don't want to call `doesFileExist` here because the file might be purely virtual.

Comment (pepeiborra) [reply session-loader/Development/IDE/Session.hs:123]: we can call `GetFileExists` which should work fine for virtual files, if you think this can be a problem in practice

**Comment by pepeiborra** [comment]
It would be cool to see the performance improvements of this change, but for that we need a benchmark example that uses TH (and doesn't have too many dependencies).

File: src/Development/IDE/Core/Compile.hs [hunk 2]
```diff
@@ -160,15 +164,13 @@ newtype RunSimplifier = RunSimplifier Bool
...
     -> TcModuleResult
     -> IO (IdeResult (SafeHaskellMode, CgGuts, ModDetails))
-compileModule (RunSimplifier simplify) packageState deps tmr =
+compileModule (RunSimplifier simplify) packageState tmr =
     fmap (either (, Nothing) (second Just)) $
     evalGhcEnv packageState $
         catchSrcErrors "compile" $ do
-            setupEnv (deps ++ [(tmrModSummary tmr, tmrModInfo tmr)])
-
+            setupEnv [(tmrModSummary tmr, tmrModInfo tmr)]
```
Comment (pepeiborra) [inline src/Development/IDE/Core/Compile.hs:173]: surprised that we don't need to setup the env with the dependencies

File: src/Development/IDE/Core/Rules.hs [hunk 3]
```diff
@@ -642,10 +639,10 @@ typeCheckRuleDefinition hsc pm isFoi source = do
 generateCore :: RunSimplifier -> NormalizedFilePath -> Action (IdeResult (SafeHaskellMode, CgGuts, ModDetails))
 generateCore runSimplifier file = do
     deps <- use_ GetDependencies file
-    (tm:tms) <- uses_ TypeCheck (file:transitiveModuleDeps deps)
+    (tm:_) <- uses_ TypeCheck (file:transitiveModuleDeps deps)
     setPriority priorityGenerateCore
     packageState <- hscEnv <$> use_ GhcSession file
-    liftIO $ compileModule runSimplifier packageState [(tmrModSummary x, tmrModInfo x) | x <- tms] tm
+    liftIO $ compileModule runSimplifier packageState tm
```
Comment (pepeiborra) [inline src/Development/IDE/Core/Rules.hs:645]: surprised that this can work with `GhcSession` and doesn't need `GhcSessionDeps`

File: src/Development/IDE/Core/Rules.hs [hunk 4]
```diff
@@ -642,10 +639,10 @@ typeCheckRuleDefinition hsc pm isFoi source = do
 generateCore :: RunSimplifier -> NormalizedFilePath -> Action (IdeResult (SafeHaskellMode, CgGuts, ModDetails))
 generateCore runSimplifier file = do
     deps <- use_ GetDependencies file
-    (tm:tms) <- uses_ TypeCheck (file:transitiveModuleDeps deps)
+    (tm:_) <- uses_ TypeCheck (file:transitiveModuleDeps deps)
```
Comment (pepeiborra) [inline src/Development/IDE/Core/Rules.hs:642]: can we drop the `transitiveModuleDeps`?

File: src/Development/IDE/Core/Rules.hs [hunk 5]
```diff
@@ -867,21 +852,39 @@ regenerateHiFile sess f = do
...
+  (ms,_) <- useWithStale_ GetModSummaryWithoutTimestamps file
+  -- A file needs object code if it uses TH or any file that depends on it uses TH
+  res <-
+    if uses_th_qq ms
+    then pure True
+    else do
+      revs <- reverseDependencies file <$> useNoFile_ GetModuleGraph
+      deps <- uses_ GetModSummaryWithoutTimestamps revs
+      pure $ any uses_th_qq deps
+  pure (Just $ BS.pack $ show $ hash res, ([], Just res))
```
Comment (pepeiborra) [inline src/Development/IDE/Core/Rules.hs:883]: `reverseDependencies` returns the transitive reverse deps.  What's the average asymptotic complexity of this rule?

Is it possible to define it recursively using the non-transitive rev deps?

**Review by pepeiborra — COMMENTED** [review]
CI benchmarks look rather useless. Can you run `cabal bench` locally and share the results?

**Comment by michaelpj** [comment]
> Any parents of the module use TH

Possibly dumb question, but: we need object code for a module's dependencies if the module uses TH. This PR achieves that by checking a module's dependants to see if they'll eventually use TH. But couldn't we just set up *rules* for computing the object code and only request it if we need it?

i.e.
- Module A uses TH, uses B, so we request object code for B
- Module B uses C, so we request the object code for C in order to produce that for B
- etc.

Isn't this the joy of building our IDE on a build system?

I haven't understood the code in detail, but it looks like you're sort of doing that already. So what stops this becoming entirely demand-driven?

File: src/Development/IDE/Core/Rules.hs (hunk 5 above)
Comment (wz1000) [reply src/Development/IDE/Core/Rules.hs:883]: Yes, good idea!

File: src/Development/IDE/Core/Rules.hs (hunk 4 above)
Comment (wz1000) [reply src/Development/IDE/Core/Rules.hs:642]: What do you think about deleting this rule?

File: src/Development/IDE/Core/Compile.hs [hunk 6]
```diff
@@ -205,6 +207,33 @@ generateByteCode hscEnv deps tmr guts =
...
+generateObjectCode hscEnv tmr = do
+    (compile_diags, Just (_, guts, _)) <- compileModule (RunSimplifier True) hscEnv tmr
+    fmap (either (, Nothing) (second Just)) $
+        evalGhcEnv hscEnv $
+          catchSrcErrors "object" $ do
+              session <- getSession
+              let summary = pm_mod_summary $ tm_parsed_module $ tmrModule tmr
+              let dot_o =  ml_obj_file (ms_location summary)
+              let session' = session { hsc_dflags = (hsc_dflags session) { outputFile = Just dot_o }}
+                  fp = replaceExtension dot_o "s"
```
[the remark this answers is not in the document]
Comment (wz1000) [reply src/Development/IDE/Core/Compile.hs:221]: See the first comment on  https://hackage.haskell.org/package/ghc-8.10.1/docs/src/DriverPhases.html

File: src/Development/IDE/Core/Compile.hs (hunk 2 above)
Comment (wz1000) [reply src/Development/IDE/Core/Compile.hs:173]: I've looked for every usage of this and made sure it is only called with `GhcSessionDeps`. In that case I don't think we need to call `setupEnv`

**Comment by wz1000** [comment]
> But couldn't we just set up _rules_ for computing the object code and only request it if we need it?

Good question. This is indeed what we were doing before, with the `GenerateBytecode` rule.

To compile a module, we need the actual typechecked AST that ghc computes after typechecking. However, to avoid excessive memory usage, we only keep typechecked ASTs for files that the user has open in their editor. For all other modules, we compute a `ModIface`(which we can use to typecheck dependent modules) and keep it in memory¸ throwing away the actual AST.

This is no good for when we need to compile object/byte code for a module. Previously, we were calling the `Typecheck` rule on such modules all over again. This meant that for projects making extensive use of TH, we were keeping typechecked ASTs in memory for all modules, even if they weren't open in the editor. Furthermore, sometimes the `GetModIface` and `Typecheck` would run typechecking for the same in parallel, leading to the bug described in #614 (which is due to an underlying race condition in GHC).

Now, we figure out if we are going to need the object code before we throw away the typechecked AST, restoring the invariant that we only keep typechecked ASTs in memory for files the user has opened. Furthermore, we avoid duplicating work caused by needing to typecheck the same file twice.

**Comment by wz1000** [comment]
There are a bunch of options here we can expose to the user -

1) Bytecode or object code?
2) Run simplifier or not? (affects IDE performace differently depending on the complexity of the TH)
3) Run desugarer for non-TH projects? If yes, desugar everything or only files of interest?

For 1) and 2), I imagine we want to set a default based on some benchmarks.

**Comment by michaelpj** [comment]
Interesting, this is potentially a usecase for Core Interface Sections, something we've been working on at IOHK. The idea being that you dump the post-desugaring Core into the interface file, and *ideally* you should then be able to resume compilation from that step. So you'd be able to do the Typecheck->ObjectCode step later without redoing work. (Speculative, obviously)

**Comment by pepeiborra** [comment]
> There are a bunch of options here we can expose to the user -
> 
> 1. Bytecode or object code?
> 2. Run simplifier or not? (affects IDE performace differently depending on the complexity of the TH)
> 3. Run desugarer for non-TH projects? If yes, desugar everything or only files of interest?
> 
> For 1) and 2), I imagine we want to set a default based on some benchmarks.

My views:

1. Since currently bytecode cannot be serialised, object code is a much better fit.
2. Never run the simplifier, until we have a direct application or user request
3. Run the desugarer always, but at a lower priority than typechecking, and only on the files of interest.

**Comment by alanz** [comment]
I thought bytecode was serialised for the external interpreter?

**Comment by wz1000** [comment]
I think I have found the root cause of the bug that #741 fixed.

We call `GHC.typecheckedModule`, which is meant for interactive use. In particular, it calls `mkBootModDetailsTc` to generate a `ModDetails`

```
-- compiler/GHC/Iface/Tidy.hs
-- This is Plan A: make a small type env when typechecking only,
-- or when compiling a hs-boot file, or simply when not using -O
--
-- We don't look at the bindings at all -- there aren't any
-- for hs-boot files
```

If we want to generate code, we need to use `tidyProgram` to generate the `ModDetails`, which requires the module to be desugared.

For now, I've changed `IDE.typecheckModule` to always desugar, as well as removing all usages of 'interactive' ghc API functions. If someone can think of a nice way to run the desugarer at a lower priority when we don't need to compile code, please let me know.

Also, @mpickering says we always need to run the simplifier, as discussed in #410. We do set `-O0`, which should mitigate the slowdown somewhat.

**Comment by ndmitchell** [comment]
The way to run it at a lower priority is to do:

```
typeCheck = rule for type check

desugar = do
    use typeCheck ...
    reschedule 0
    do desugaring

main = depend on desugar
```

That says start with desugaring, but once you have type checked, put yourself to the back of the queue behind all other type checks.

**Comment by wz1000** [comment]
@ndmitchell what happens if a rule with high priority `uses` a rule with low priority?

**Comment by ndmitchell** [comment]
The rule with high priority will wait for the low priority one to finish - you get priority inversion - so its generally not a good thing to do (although its not that harmful, unless you have a lot of normal priority stuff waiting around)

**Comment by wz1000** [comment]
I'm a bit confused about the meaning of priorities. We have the following in `ghcide`, 

```haskell
newtype Priority = Priority Double

setPriority :: Priority -> Action ()
setPriority (Priority p) = reschedule p

priorityTypeCheck :: Priority
priorityTypeCheck = Priority 0

priorityGenerateCore :: Priority
priorityGenerateCore = Priority (-1)

priorityFilesOfInterest :: Priority
priorityFilesOfInterest = Priority (-2)
```

Which one of these will be given preference by the scheduler?

Reading the `shake` source for `reschedule` only adds to my confusion...
```haskell
reschedule x = do
    (wait, _) <- actionAlwaysRequeuePriority (PoolDeprioritize $ negate x) $ pure ()
```

Too many negations for me to follow 😕

**Comment by wz1000** [comment]
Getting some strange failures when I add desugaring to kick ¯\_(ツ)_/¯

```
  cpp
    cpp-error:                                                                                            FAIL (1.95s)
      test/src/Development/IDE/Test.hs:44:
      Could not find (DsError,(2,1),"error: unterminated",Nothing) in List [Diagnostic {_range = Range {_start = Position {_line = 2, _character = -1}, _end = Position {_line = 2, _character = -1}}, _severity = Just DsError, _code = Nothing, _source = Just "CPP", _message = " error: unterminated #ifdef\n    3 | #ifdef FOO\n      | \n", _tags = Nothing, _relatedInformation = Nothing}]
    cpp-ghcide:                                                                                           OK (1.24s)
  diagnostics
    fix syntax error:                                                                                     FAIL (0.64s)
      test/src/Development/IDE/Test.hs:115:
      Incorrect number of diagnostics for Uri {getUri = "file:///tmp/extra-dir-37097490727748/Testing.hs"}, expected [] but got List [Diagnostic {_range = Range {_start = Position {_line = 0, _character = 15}, _end = Position {_line = 0, _character = 19}}, _severity = Just DsError, _code = Nothing, _source = Just "parser", _message = "parse error on input \8216wher\8217", _tags = Nothing, _relatedInformation = Nothing},Diagnostic {_range = Range {_start = Position {_line = 0, _character = 15}, _end = Position {_line = 0, _character = 19}}, _severity = Just DsError, _code = Nothing, _source = Just "parser", _message = "parse error on input \8216wher\8217", _tags = Nothing, _relatedInformation = Nothing}]
    introduce syntax error:                                                                               FAIL (1.18s)
      test/src/Development/IDE/Test.hs:78:
      Got unexpected diagnostics for Uri {getUri = "file:///tmp/extra-dir-37097490727749/Testing.hs"} got List [Diagnostic {_range = Range {_start = Position {_line = 0, _character = 15}, _end = Position {_line = 0, _character = 21}}, _severity = Just DsError, _code = Nothing, _source = Just "parser", _message = "parse error on input \8216wherre\8217", _tags = Nothing, _relatedInformation = Nothing},Diagnostic {_range = Range {_start = Position {_line = 0, _character = 15}, _end = Position {_line = 0, _character = 21}}, _severity = Just DsError, _code = Nothing, _source = Just "parser", _message = "parse error on input \8216wherre\8217", _tags = Nothing, _relatedInformation = Nothing}]
```

First one is particularly spooky. `Position {_line = 2, _character = -1}}` ?

Otherwise, I think this is ready after a re-review.

**Comment by pepeiborra** [comment]
This looks fantastic, great job @wz1000, hopefully fixing all the TH bugs in the process. 

I will find the time to re-review tomorrow evening. In the meantime:

- could you clarify the shape of the Shake graph after these changes? Ideally we put desugaring as a separate step after typechecking, so that we can get diagnostics as early as possible.
- have you done any benchmarks? What's the plan to test on a TH example?

**Comment by wz1000** [comment]
The changes to the shake graph are as follows:

1. `Typecheck` doesn't write out (or generate) any iface files, it just does whats stated on the tin
2. `GetModIface`/`GetModIfaceFromDisk` is where all the magic happens.
   - We use `NeedsObjectCode` to figure out if we need to compile the module
   - If we do, we `use_ GenerateCore` for FOIs, or call `generateCoreDefinition` for non-FOIs
   - If need object code and generated core, we use that to generate a full `Iface` file, along with object code
   - Otherwise, we just generate a 'simple' iface file by calling 'mkIfaceTc`
   - In the end, we figure out we need to write the iface file on disk, and do so if required
3. `kick` now calls `GenerateCore` to produce warnings, and `GetHieAST` to write out hie files.

Benchmarks and fixing the remaining tests are next on my agenda.

I'm still conflicted about whether we need to keep the result of `GenerateCore` in the graph, or if we could just throw it away.

File: src/Development/IDE/Core/Rules.hs [hunk 7]
```diff
@@ -392,7 +393,8 @@ rawDependencyInformation fs = do
       -- If we have, just return its Id but don't update any of the state.
       -- Otherwise, we need to process its imports.
       checkAlreadyProcessed f $ do
-          al <- lift $ modSummaryToArtifactsLocation f <$> use_ GetModSummaryWithoutTimestamps f
+          msum <- lift $ use GetModSummaryWithoutTimestamps f
```
Comment (wz1000) [inline src/Development/IDE/Core/Rules.hs:396]: We don't want to fail here, since the result of `GetModIface` now depends on the entire graph's headers/modsummaries

**Comment by wz1000** [comment]
I'm using the following configuration for benchmarking:

```yaml
example:
    name: haskell-lsp-types
    version: 0.22.0.0
    # # path: path/to/example
    module: src/Language/Haskell/LSP/Types/Lens.hs
```

Here are the results:

```csv
version    name                         success   samples   startup              setup                userTime               delayedTime             totalTime             maxResidency   allocatedBytes
upstream   hover                        True      100       10.614806232000001   0.0                  0.10257583399999999    3.340193600000001e-2    0.14050068000000002   319777184      6115153688
HEAD       hover                        True      100       7.7185963520000005   0.0                  0.45777121499999973    3.5779573e-2            0.497748911           164670560      2716464040
upstream   edit                         True      100       9.299547219          0.0                  27.364207991           0.20843280399999992     27.578036549          339209832      47839423136
HEAD       edit                         True      100       8.063393366          0.0                  38.008773957999985     0.6213196139999998      38.635416729          166595120      68167264816
upstream   getDefinition                True      100       9.299885888          0.0                  6.3038403e-2           2.0231722999999993e-2   8.6907673e-2          320671832      6090475128
HEAD       getDefinition                True      100       8.01779254           0.0                  7.801578100000002e-2   0.39756615800000006     0.479599582           164391728      2692337384
upstream   hover after edit             True      100       9.569584439          0.0                  0.649604651            27.137278584000008      27.792731983000003    333945152      55002822280
HEAD       hover after edit             True      100       7.8474618430000005   0.0                  1.2949229160000006     76.95365204099998       78.255706743          175195272      135863207032
upstream   completions after edit       True      100       9.292151514          0.0                  6.870972618000005      21.154938894000004      28.032305479          339928928      69540079968
HEAD       completions after edit       True      100       8.354598959          0.0                  7.296952549000002      22.032134922999994      29.337312232000002    177797184      65961116000
upstream   code actions                 True      100       9.418781461          0.7522214460000001   0.6891327480000001     4.1814197000000004e-2   0.737375199           365674056      8408618680
HEAD       code actions                 True      100       8.478195708000001    0.8031139460000001   0.9741454130000003     0.28154403900000013     1.262175481           222930536      5155011264
upstream   code actions after edit      True      100       9.205042200000001    0.0                  65.97669554199999      3.9817547000000016e-2   66.02095223           388161080      126965911240
HEAD       code actions after edit      True      100       8.362657242000001    0.0                  73.54964010300002      0.4446636240000001      74.000585133          245196664      116454301472
upstream   documentSymbols after edit   True      100       9.106493854          0.0                  0.4217413190000001     0.5491246350000001      0.977217133           328066504      8863760416
HEAD       documentSymbols after edit   True      100       10.102078910000001   0.0                  0.4835813629999999     1.193969614000001       1.6880487540000002    165829184      6147453776
```

User time and total time increase, max residency is halved.

**Comment by wz1000** [comment]
Here are the results if we don't desugar and just typecheck

```
version    name                         success   samples   startup              setup                userTime               delayedTime             totalTime              maxResidency   allocatedBytes
upstream   hover                        True      100       9.775739957          0.0                  7.509792200000004e-2   2.3456665999999994e-2   0.10212122800000001    319672744      6128870352
HEAD       hover                        True      100       7.677350291000001    0.0                  0.5480348690000003     3.4458624000000014e-2   0.586015334            164726944      2717224448
upstream   edit                         True      100       9.43701669           0.0                  24.708787200000003     0.217431362             24.931171044000003     339036160      47838467520
HEAD       edit                         True      100       7.486315764          0.0                  22.994777094999996     0.576966195             23.576577878000002     188922200      40749324328
upstream   getDefinition                True      100       9.275651766000001    0.0                  6.240487899999998e-2   2.4159567e-2            9.006775900000001e-2   320183152      6105467816
HEAD       getDefinition                True      100       7.625304047          0.0                  0.2696263159999998     0.5086219970000002      0.7818169930000001     164392840      2695024224
upstream   hover after edit             True      100       9.439057042          0.0                  0.6495210729999996     27.40231568300001       28.057617792000002     334082656      54990381576
HEAD       hover after edit             True      100       7.530357511          0.0                  1.1434777970000005     76.56428582400001       77.714699726           187706984      135592405328
upstream   completions after edit       True      100       9.397739779          0.0                  6.843254851000001      21.314822434000003      28.165777491           339736568      69531959720
HEAD       completions after edit       True      100       7.456776028          0.0                  6.937418449            19.876863895            26.821768431000002     190212280      62544143512
upstream   code actions                 True      100       9.308324401          0.780531033          0.7470925310000002     4.502434800000001e-2    0.797485121            365567584      8405471256
HEAD       code actions                 True      100       7.5375515470000005   0.8169353610000001   0.8686975460000003     0.6868279529999997      1.5637661770000002     246016776      4879625856
upstream   code actions after edit      True      100       9.41876682           0.0                  66.48259642200003      3.841946e-2             66.525442083           387453680      126967822672
HEAD       code actions after edit      True      100       7.496058034000001    0.0                  63.494944305000004     0.6717071160000001      64.170956139           257168424      115286460936
upstream   documentSymbols after edit   True      100       9.233068117          0.0                  0.4202038720000001     0.52859087              0.956152438            328096856      8845712320
HEAD       documentSymbols after edit   True      100       7.518854782000001    0.0                  0.666159482            1.035005161             1.7089357550000002     180192304      5353000216
```

```diff
diff --git a/src/Development/IDE/Core/OfInterest.hs b/src/Development/IDE/Core/OfInterest.hs
index 1caacfc3..dda25030 100644
--- a/src/Development/IDE/Core/OfInterest.hs
+++ b/src/Development/IDE/Core/OfInterest.hs
@@ -94,10 +94,10 @@ kick = mkDelayedAction "kick" Debug $ do
     liftIO $ progressUpdate KickStarted
 
     -- Update the exports map for the project
-    results <- uses GenerateCore $ HashMap.keys files
+    results <- uses TypeCheck $ HashMap.keys files
     ShakeExtras{exportsMap} <- getShakeExtras
     let mguts = catMaybes results
-        !exportsMap' = createExportsMapMg mguts
+        !exportsMap' = createExportsMapTc $ map tmrTypechecked mguts
     liftIO $ modifyVar_ exportsMap $ evaluate . (exportsMap' <>)
```

**Comment by wz1000** [comment]
If we use bytecode instead of object code, and don't desugar in kick, here is what we get:

```
version    name                         success   samples   startup              setup                userTime               delayedTime             totalTime            maxResidency   allocatedBytes
upstream   hover                        True      100       10.891087254         0.0                  9.209635400000003e-2   2.7845442000000005e-2   0.123939107          320352552      6135043000
HEAD       hover                        True      100       10.904560363         0.0                  0.280567656            3.521885500000002e-2    0.319338823          282604048      6249242712
upstream   edit                         True      100       9.811893251          0.0                  28.136112453000003     0.24779284699999996     28.389346223         340329488      47839749088
HEAD       edit                         True      100       10.118380068         0.0                  245.20731385400006     0.28579294200000005     245.50228024600003   489770408      440044434672
upstream   getDefinition                True      100       9.386153363          0.0                  6.171676200000002e-2   2.0830596999999996e-2   8.5869031e-2         320234360      6101097840
HEAD       getDefinition                True      100       10.123143692000001   0.0                  6.514175700000001e-2   0.23917315700000008     0.308031795          283381232      6222840680
upstream   hover after edit             True      100       9.385658361          0.0                  0.6469818239999999     32.112947690999995      32.766236413         331231416      54991535400
HEAD       hover after edit             True      100       10.045937113         0.0                  2.628170223999999      256.7142117480001       259.348206441        486343256      486450681840
upstream   completions after edit       True      100       9.385118779          0.0                  6.7748024220000005     21.02937944699999       27.811350462         339541104      69533543008
HEAD       completions after edit       True      100       9.122527803          0.0                  11.919567483           220.11206598000004      232.039704228        482652976      462159548352
upstream   code actions                 True      100       9.204064802000001    0.7599791300000001   0.8867297640000003     5.1324132e-2            0.944999629          365385928      8410147512
HEAD       code actions                 True      100       9.287688051          2.4146111510000003   1.0743402820000005     0.13389134              1.2140506320000002   426299520      12438797472
upstream   code actions after edit      True      100       9.170937589000001    0.0                  65.652404632           3.9814251000000016e-2   65.696594452         387002776      127032999936
HEAD       code actions after edit      True      100       9.925779058          0.0                  268.79041496599984     0.12485944300000001     268.920168937        515844856      519647459384
upstream   documentSymbols after edit   True      100       8.971234719          0.0                  0.4269711559999999     0.5216603530000001      0.9547841890000001   328411872      8856234008
HEAD       documentSymbols after edit   True      100       11.055146743         0.0                  0.879312115            3.0882921830000005      3.974355355          384377232      15598340128
```

Something is clearly going wrong somewhere, or we would expect similar performance to upstream

**Comment by jneira** [comment]
I am afraid my last pr adding win tests are not passing :worried: 
Some of the seems to be transient but one is failing for all versions:
```
add missing module (non workspace):                                                                   FAIL (0.59s)
      test/src\Development\IDE\Test.hs:115:
      Incorrect number of diagnostics for Uri {getUri = "file:///C:/Users/VssAdministrator/AppData/Local/Temp/ModuleB.hs"}, expected [] but got List [Diagnostic {_range = Range {_start = Position {_line = 0, _character = 0}, _end = Position {_line = 1, _character = 0}}, _severity = Just DsError, _code = Nothing, _source = Just "compiler", _message = "File does not exist: C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\ModuleB.hs", _tags = Nothing, _relatedInformation = Nothing}]
```

**Comment by wz1000** [comment]
OK, the discrepancy earlier was due to `HiFileStable` not being early-cutoff. This would cause `GetModIfaceFromDisk` to rerun every single time, causing a retypecheck (since we can't serialize `Bytecode` to disk)

Here are the results(bytecode, no-desugar) after making `HiFileStable` early-cutoff:

```
version    name                         success   samples   startup             setup                userTime               delayedTime             totalTime             maxResidency   allocatedBytes
upstream   hover                        True      100       9.248425724         0.0                  7.698714399999998e-2   2.6993262999999997e-2   0.10738317200000001   321210136      6141914016
HEAD       hover                        True      100       9.428752561000001   0.0                  0.25510042999999993    3.2758059e-2            0.291588304           283326104      6263528680
upstream   edit                         True      100       11.094691829        0.0                  24.701751852999998     0.22562032300000007     24.932668281          338631088      47864225688
HEAD       edit                         True      100       9.275243025         0.0                  23.365355352999995     0.40143874100000004     23.771878369000003    314904960      45485749616
upstream   getDefinition                True      100       11.623423209        0.0                  6.484041000000001e-2   2.5647346e-2            9.40082e-2            321079160      6111860864
HEAD       getDefinition                True      100       9.296106497         0.0                  6.021235800000001e-2   0.21477420599999988     0.27853474500000003   282133376      6245751568
upstream   hover after edit             True      100       9.547423465000001   0.0                  0.6424842230000001     36.084871441999994      36.733664275          333369376      55040321928
HEAD       hover after edit             True      100       9.476150579         0.0                  0.8120755270000004     46.69905038399999       47.517313449          326261768      91910826672
upstream   completions after edit       True      100       9.387774878         0.0                  6.815884588000003      21.279297885000002      28.101604971          341073632      69583845408
HEAD       completions after edit       True      100       9.328481924         0.0                  7.048700538000003      20.201057674999998      27.257390883000003    324386448      67633989248
upstream   code actions                 True      100       9.551522439000001   0.759548854          0.8831020840000002     5.175816700000003e-2    0.9423475910000001    365629560      8416361976
HEAD       code actions                 True      100       9.289200113         0.7257372080000001   0.7778286260000005     0.1365894               0.920870417           340242280      8493467136
upstream   code actions after edit      True      100       9.522357067         0.0                  67.11034028899998      3.8492919e-2            67.153399938          387434272      126964220400
HEAD       code actions after edit      True      100       9.125311255         0.0                  66.13131359399999      0.133412795             66.269097395          374464752      124578185432
upstream   documentSymbols after edit   True      100       10.159089673        0.0                  0.4486661400000001     3.5024009139999994      3.95745191            439348912      16148142832
HEAD       documentSymbols after edit   True      100       9.379302618         0.0                  0.4262143980000003     0.7412191119999996      1.173183909           317757296      9056347984
```

I will compute and post the results for the other configurations now.

**Comment by wz1000** [comment]
No Desugar, Object Code:

```
version    name                         success   samples   startup              setup                userTime               delayedTime             totalTime              maxResidency   allocatedBytes
upstream   hover                        True      100       11.785200168000001   0.0                  7.943398300000001e-2   2.8286042999999997e-2   0.111288037            321803656      6140556552
HEAD       hover                        True      100       9.343552638          0.0                  0.6949281559999999     4.2667355e-2            0.742495706            165690400      2727491184
upstream   edit                         True      100       10.440676489000001   0.0                  31.575976559000004     4.953585000000002e-2    31.631398245000003     339433560      47893483336
HEAD       edit                         True      100       9.150219489000001    0.0                  29.287900517000004     0.9062445280000004      30.199965515000002     189048672      40747147088
upstream   getDefinition                True      100       10.979775062         0.0                  6.220997599999998e-2   2.2628099e-2            8.869044000000001e-2   320451968      6121450800
HEAD       getDefinition                True      100       9.440941147          0.0                  7.404820800000003e-2   0.6319512569999998      0.711199125            165328352      2705782224
upstream   hover after edit             True      100       11.239479522         0.0                  0.7176793110000004     32.289810153000005      33.01366505            333767592      55026924120
HEAD       hover after edit             True      100       9.897300082000001    0.0                  1.0711574729999995     90.89172193799998       91.970725355           187380048      135608612272
upstream   completions after edit       True      100       11.143692736         0.0                  7.980520569000002      26.213356339000004      34.203302914000005     338415376      69543347128
HEAD       completions after edit       True      100       7.821178513          0.0                  7.498439339000003      22.789826441            30.296667358           191001816      62559539200
upstream   code actions                 True      100       11.577994268000001   0.8801105210000001   0.8326821280000001     4.908473899999999e-2    0.88932029             366508640      8426906296
HEAD       code actions                 True      100       8.298276463          0.7260953330000001   0.7087386960000001     0.715315894             1.430534272            247591648      4891916408
upstream   code actions after edit      True      100       10.401668688         0.0                  78.48811591200003      4.237389800000001e-2    78.535801686           388395872      126963235768
HEAD       code actions after edit      True      100       8.976084469          0.0                  78.843109963           0.7261178799999999      79.575097451           263334072      115298173664
upstream   documentSymbols after edit   True      100       11.150307419         0.0                  0.45360250900000004    3.624175715000001       4.084975216            439113600      16144420856
HEAD       documentSymbols after edit   True      100       9.731794409          0.0                  0.4609114760000001     1.177971077000001       1.648493436            181190136      5367269016
```

**Comment by wz1000** [comment]
Desugar, Object Code (final version):

```
version    name                         success   samples   startup              setup         userTime                delayedTime             totalTime              maxResidency   allocatedBytes
upstream   hover                        True      100       10.134264808000001   0.0           7.590776999999999e-2    2.5503662000000003e-2   0.104990253            321541376      6147737912
HEAD       hover                        True      100       8.215322027000001    0.0           0.43749363900000005     3.501751099999998e-2    0.47626461600000003    165649240      2720914872
upstream   edit                         True      100       10.253288863         0.0           25.620408799999993      4.764400800000001e-2    25.673410342           339294472      47851005368
HEAD       edit                         True      100       8.240138369          0.0           38.09972816             0.6257690830000003      38.730842339000006     167666200      68183879632
upstream   getDefinition                True      100       10.216878373         0.0           5.5551976999999995e-2   1.7521253e-2            7.637429400000001e-2   321073680      6108180432
HEAD       getDefinition                True      100       8.368589887          0.0           6.1249428000000036e-2   0.3921647969999999      0.45782061300000004    165298560      2704806256
upstream   hover after edit             True      100       11.701408612000002   0.0           0.8039888849999994      30.333118486            31.1431158             333474304      55000043624
HEAD       hover after edit             True      100       8.259664977          0.0           1.129828484             79.49919962400001       80.636104461           170813480      135927249616
upstream   completions after edit       True      100       12.031567913         0.0           9.262992396000001       30.755045869            40.027056783           341183040      69549963968
HEAD       completions after edit       True      100       8.335173657          0.0           6.907124970999999       20.558625391000003      27.474603372           179137968      65898836672
upstream   code actions                 True      100       12.312523629000001   1.011998497   0.931135539             5.765050100000001e-2    0.998056856            364964792      8419854928
HEAD       code actions                 True      100       8.218620566          0.765151197   0.9519099389999999      0.2893928579999999      1.2475695150000001     224004424      5167683768
upstream   code actions after edit      True      100       11.816173703         0.0           88.63161126800007       4.7925856e-2            88.68536465400001      388469496      126946074208
HEAD       code actions after edit      True      100       8.220013333          0.0           66.022011344            0.4334701160000001      66.460468852           246007024      116463179360
upstream   documentSymbols after edit   True      100       11.705031859         0.0           0.51709987              0.6730954800000002      1.199390025            329378872      8871088144
HEAD       documentSymbols after edit   True      100       8.261329688          0.0           0.43914058100000003     1.1223097280000005      1.568958829            166759216      6168963160
```

**Comment by pepeiborra** [comment]
* How much TH is there in the example project? All the modules?
* Can we have benchmarks for the Cabal-3.0.0.0 example? I want to see the impact for a non TH project.

The total times are odd. "upstream - code actions after edit - total time" takes all of 3 different values, 68s, 78s and 88s, in the last 3 benchmarks. Must have been getting warmer in your room as the benchmarks were running.

The allocations on the other hand are remarkably consistent, so I'll be looking at those as a proxy for time performance below.

* Hover after edit has become much slower.
  * 67% slower for bytecode.
  * 146% slower for object code (both with and without desugaring). 
  * This is a bit worrying.  Is that because producing `.hie` files is more expensive now? Why?
* Edit is faster except when desugaring is turned on, then it becomes 42% slower. Seems reasonable

Max residency is down quite a bit with object code, I imagine it's because we're no longer keeping bytecode in memory for the entire project. This is crucial for scalability in larger TH codebases, awesome result.

File: src/Development/IDE/Core/Compile.hs [hunk 8]
```diff
@@ -123,26 +129,95 @@ typecheckModule :: IdeDefer
...
+        <- liftIO $ hscTypecheckRename hsc_env_tmp ms $
+                       HsParsedModule { hpm_module = parsedSource pmod,
+                                        hpm_src_files = pm_extra_src_files pmod,
+                                        hpm_annotations = pm_annotations pmod }
+  let rn_info = case mrn_info of
+        Just x -> x
+        Nothing -> error "no renamed info tcRnModule"
+  pure (TcModuleResult pmod rn_info tc_gbl_env False)
+
+mkTcModuleResultNoCompile :: HscEnv -> TcModuleResult -> IO HiFileResult
```
Comment (pepeiborra) [inline src/Development/IDE/Core/Compile.hs:166]: Naming choice seems odd. `mkHiFileResultNoCompile` perhaps?

File: src/Development/IDE/Core/Compile.hs [hunk 9]
```diff
@@ -123,26 +129,95 @@ typecheckModule :: IdeDefer
...
+#endif
+  let mod_info = HomeModInfo iface details Nothing
+  pure $! HiFileResult ms mod_info
+
+mkTcModuleResultCompile
+    :: HscEnv
+    -> TcModuleResult
+    -> ModGuts
+    -> IO (IdeResult HiFileResult)
+mkTcModuleResultCompile session' tcm simplified_guts = catchErrs $ do
```
Comment (pepeiborra) [inline src/Development/IDE/Core/Compile.hs:186]: Naming choice seems odd. `mkHiFileResultCompile` perhaps?

**Comment by wz1000** [comment]
> How much TH is there in the example project? All the modules?

Most of them, yes. The `Lens` module is near the top of the hierarchy, while still being pretty complex itself. Mostly deriving aeson instances. `haskell-lsp-types` takes quite a while to compile.

> Can we have benchmarks for the Cabal-3.0.0.0 example? I want to see the impact for a non TH project.

Cabal results (from Azure):

```
version    name                         success   samples   startup              setup         userTime              delayedTime             totalTime            maxResidency   allocatedBytes
upstream   hover                        True      100       25.424601648000003   0.0           0.238279021           4.651216700000001e-2    0.291243169          500763480      23222128280
HEAD       hover                        True      100       21.968417417         0.0           0.15362439600000002   4.462610100000001e-2    0.204113059          368613792      22063094896
upstream   edit                         True      100       25.522049563000003   0.0           30.173149460000005    7.635390700000004e-2    30.257776481         518169200      60354267824
HEAD       edit                         True      100       21.758806720000003   0.0           38.954167809000005    4.9435851999999995e-2   39.013062094000006   311366232      69484386616
upstream   getDefinition                True      100       25.247210147         0.0           0.17981466899999998   3.607049899999999e-2    0.221511637          499957648      23157458872
HEAD       getDefinition                True      100       21.786835857         0.0           0.10430183599999998   3.806296700000001e-2    0.150408773          347736568      22008917632
upstream   hover after edit             True      100       25.433282365         0.0           1.825791864           38.50469803400003       40.339351041         516834648      72220404040
HEAD       hover after edit             True      100       22.172740176         0.0           1.655587471           36.26843765799999       37.931728284         302107840      70780029200
upstream   completions after edit       True      100       25.487009924000002   0.0           3.227955087           33.60961624000001       36.845723992         529002768      68607483624
HEAD       completions after edit       True      100       22.099746181         0.0           2.980362291000001     33.619646204000006      36.60778177          370208016      68033556064
upstream   code actions                 True      100       24.996228055000003   2.465269794   1.3766892400000008    4.928437200000002e-2    1.4364545370000001   540654680      26187157120
HEAD       code actions                 True      100       22.385750689         1.211969102   1.345687483           5.0815959e-2            1.4054241920000001   330886208      24495449520
upstream   code actions after edit      True      100       24.984587877000003   0.0           76.421018242          5.753962399999998e-2    76.485958334         543750784      107071521064
HEAD       code actions after edit      True      100       23.248845105         0.0           87.65767697599998     6.893526500000001e-2    87.73452116700001    287833376      116182704832
upstream   documentSymbols after edit   True      100       24.842966308         0.0           2.612667494           1.2657600680000003      3.891133281          516249688      31454107016
HEAD       documentSymbols after edit   True      100       22.220106758         0.0           2.4726671010000008    2.4616957030000015      4.967755514          359878064      30302539584
```

> This is a bit worrying. Is that because producing .hie files is more expensive now? Why?

The only change is that hie files aren't generated along with typechecking, but on demand. Maybe the priorities are messing the result up. I will experiment with them later, and try putting `GetHieASTs` in `kick`, to see if that improves things.

File: src/Development/IDE/Core/Rules.hs [hunk 10]
```diff
@@ -203,8 +204,8 @@ getHomeHieFile f = do
       wait <- lift $ delayedAction $ mkDelayedAction "OutOfDateHie" L.Info $ do
         hsc <- hscEnv <$> use_ GhcSession f
         pm <- use_ GetParsedModule f
-        source <- getSourceFileSource f
-        typeCheckRuleDefinition hsc pm NotFOI (Just source)
+        (_, mtm)<- typeCheckRuleDefinition hsc pm
+        mapM_ (getHieAstRuleDefinition f hsc) mtm
```
Comment (pepeiborra) [inline src/Development/IDE/Core/Rules.hs:208]: Add a comment to note that we are calling this just for the side effect

**Review by pepeiborra — COMMENTED** [review]
> The only change is that hie files aren't generated along with typechecking, but on demand. Maybe the priorities are messing the result up. I will experiment with them later, and try putting `GetHieASTs` in `kick`, to see if that improves things.

I was about to suggest this (getHieASTs in kick) in my review.

**Review by pepeiborra — APPROVED** [review]
No major concerns from my side. Nice job again!

File: src/Development/IDE/Core/Rules.hs [hunk 11]
```diff
@@ -263,6 +264,7 @@ priorityFilesOfInterest = Priority (-2)
 -- and https://github.com/mpickering/ghcide/pull/22#issuecomment-625070490
 getParsedModuleRule :: Rules ()
 getParsedModuleRule = defineEarlyCutoff $ \GetParsedModule file -> do
+    _ <- use_ GetModSummaryWithoutTimestamps file -- Fail if we can't even parse the ModSummary
```
[the remark this answers is not in the document]
Comment (wz1000) [reply src/Development/IDE/Core/Rules.hs:267]: Some tests were failing because we reported parse errors twice - once when we tried to parse the `ModSummary`, and once when we tried to parse the actual source. This was the simplest way I could think of to fix it.

File: src/Development/IDE/Core/Rules.hs (hunk 7 above)
Comment (wz1000) [reply src/Development/IDE/Core/Rules.hs:397]: If even one module header failed to parse here, `NeedsObjCode` would fail, which would make typechecking fail for everything in the entire project.

File: src/Development/IDE/Core/Rules.hs [hunk 12]
```diff
@@ -862,26 +821,70 @@ regenerateHiFile sess f = do
...
+                hiDiags <- case res of
+                  Just hiFile
+                    | not $ tmrDeferedError tmr ->
+                      liftIO $ writeHiFile hsc hiFile
+                  _ -> pure []
+
+                -- Write hie file
+                (gDiags, masts) <- liftIO $ generateHieAsts hsc tmr
+                wDiags <- forM masts $ \asts ->
+                  liftIO $ writeHieFile hsc (tmrModSummary tmr) (tcg_exports $ tmrTypechecked tmr) asts $ maybe "" T.encodeUtf8 contents
```
[the remark this answers is not in the document]
Comment (wz1000) [reply src/Development/IDE/Core/Rules.hs:847]: Yes, one is called for non-FOIs, and one is called for FOIs.

File: src/Development/IDE/Core/Rules.hs [hunk 13]
```diff
@@ -820,30 +758,51 @@ getModSummaryRule = do
...
+          , not (tmrDeferedError tmr) -> liftIO $ writeHiFile hsc hiFile
+        _ -> pure []
+      return (fp, (diags++hiDiags, hiFile))
     NotFOI -> do
-      hiFile <- use GetModIfaceFromDisk f
-      let fp = hiFileFingerPrint <$> hiFile
-      return (fp, ([], hiFile))
+      hiFile <- use_ GetModIfaceFromDisk f
+      let fp = hiFileFingerPrint hiFile
+      return (Just fp, ([], Just hiFile))
```
[the remark this answers is not in the document]
Comment (wz1000) [reply src/Development/IDE/Core/Rules.hs:795]: leftover from some hacking

File: src/Development/IDE/Core/Rules.hs (hunk 11 above)
[the remark this answers is not in the document]
Comment (pepeiborra) [reply src/Development/IDE/Core/Rules.hs:267]: seems reasonable

File: src/Development/IDE/Core/Rules.hs (hunk 7 above)
Comment (pepeiborra) [reply src/Development/IDE/Core/Rules.hs:397]: I see, because of the `GetModuleGraph` dependency. So you have made this code able to tolerate failures. Fair enough

**Comment by wz1000** [comment]
Adding `GetHieAst` to kick doesn't seem to help. Neither does removing the `setPriority` calls.

No `GetHieAsts` in kick (baseline):

```
version    name                         success   samples   startup              setup         userTime                delayedTime             totalTime              maxResidency   allocatedBytes
upstream   hover                        True      100       10.134264808000001   0.0           7.590776999999999e-2    2.5503662000000003e-2   0.104990253            321541376      6147737912
HEAD       hover                        True      100       8.215322027000001    0.0           0.43749363900000005     3.501751099999998e-2    0.47626461600000003    165649240      2720914872
upstream   edit                         True      100       10.253288863         0.0           25.620408799999993      4.764400800000001e-2    25.673410342           339294472      47851005368
HEAD       edit                         True      100       8.240138369          0.0           38.09972816             0.6257690830000003      38.730842339000006     167666200      68183879632
upstream   getDefinition                True      100       10.216878373         0.0           5.5551976999999995e-2   1.7521253e-2            7.637429400000001e-2   321073680      6108180432
HEAD       getDefinition                True      100       8.368589887          0.0           6.1249428000000036e-2   0.3921647969999999      0.45782061300000004    165298560      2704806256
upstream   hover after edit             True      100       11.701408612000002   0.0           0.8039888849999994      30.333118486            31.1431158             333474304      55000043624
HEAD       hover after edit             True      100       8.259664977          0.0           1.129828484             79.49919962400001       80.636104461           170813480      135927249616
upstream   completions after edit       True      100       12.031567913         0.0           9.262992396000001       30.755045869            40.027056783           341183040      69549963968
HEAD       completions after edit       True      100       8.335173657          0.0           6.907124970999999       20.558625391000003      27.474603372           179137968      65898836672
upstream   code actions                 True      100       12.312523629000001   1.011998497   0.931135539             5.765050100000001e-2    0.998056856            364964792      8419854928
HEAD       code actions                 True      100       8.218620566          0.765151197   0.9519099389999999      0.2893928579999999      1.2475695150000001     224004424      5167683768
upstream   code actions after edit      True      100       11.816173703         0.0           88.63161126800007       4.7925856e-2            88.68536465400001      388469496      126946074208
HEAD       code actions after edit      True      100       8.220013333          0.0           66.022011344            0.4334701160000001      66.460468852           246007024      116463179360
upstream   documentSymbols after edit   True      100       11.705031859         0.0           0.51709987              0.6730954800000002      1.199390025            329378872      8871088144
HEAD       documentSymbols after edit   True      100       8.261329688          0.0           0.43914058100000003     1.1223097280000005      1.568958829            166759216      6168963160
```

`GetHieAsts` in kick, after `GenerateCore`:

```
version    name                         success   samples   startup              setup         userTime               delayedTime             totalTime             maxResidency   allocatedBytes
upstream   hover                        True      100       10.480638833         0.0           8.955537299999998e-2   2.9213159000000006e-2   0.12267512300000001   321557568      6141256512
HEAD       hover                        True      100       7.728103687000001    0.0           0.397651645            3.0258001000000007e-2   0.431272951           165715888      2726378408
upstream   edit                         True      100       10.289357655         0.0           29.658225465000005     0.22801466800000014     29.891951305000003    339823280      47855379360
HEAD       edit                         True      100       7.617668485          0.0           39.086477091999996     0.5925168530000002      39.684251027          171289728      72977064712
upstream   getDefinition                True      100       11.305774814000001   0.0           7.265682800000003e-2   2.4276802999999993e-2   0.100716226           321054688      6114908592
HEAD       getDefinition                True      100       7.767921090000001    0.0           4.5669693e-2           0.37852691300000024     0.427734612           165459984      2711814392
upstream   hover after edit             True      100       10.544795148         0.0           0.7527543289999994     33.815146453000004      34.573929407          333860768      55002503576
HEAD       hover after edit             True      100       8.710477287          0.0           1.2360339540000005     83.560619291            84.804345149          179411192      135962005544
upstream   completions after edit       True      100       11.632372483000001   0.0           8.381041169000005      27.514083123000006      35.904776466          340902600      69521760416
HEAD       completions after edit       True      100       8.737494389          0.0           7.220561144000001      22.488068868000003      29.720047513          179420560      66001744968
upstream   code actions                 True      100       10.554758488000001   0.859808208   0.7730778049999997     4.5911674000000006e-2   0.8251470510000001    366519008      8421339328
HEAD       code actions                 True      100       8.595893097000001    1.077405195   0.7765309570000001     0.26745027800000015     1.0507687620000001    225989952      5288294528
upstream   code actions after edit      True      100       10.389283163         0.0           77.41910598699998      3.9468378000000005e-2   77.46374986800001     388379208      126987253216
HEAD       code actions after edit      True      100       8.493706149000001    0.0           72.41118718900003      0.4856799040000003      72.902948663          253915832      116620085680
upstream   documentSymbols after edit   True      100       10.228902693         0.0           0.474310696            0.6150169199999999      1.097750782           329441472      8853117384
HEAD       documentSymbols after edit   True      100       9.320803584          0.0           0.5583431529999999     1.2574171439999984      1.8282021370000001    171237504      6362240568
```

`GetHieAsts` in kick, before `GenerateCore`:

```
version    name                         success   samples   startup              setup                userTime               delayedTime             totalTime             maxResidency   allocatedBytes
upstream   hover                        True      100       10.303325229         0.0                  8.982343400000004e-2   2.996870000000001e-2    0.12344808            321893776      6135406240
HEAD       hover                        True      100       8.733048096000001    0.0                  0.49022497099999984    3.7919233e-2            0.5328425950000001    165770608      2723440512
upstream   edit                         True      100       10.333786691         0.0                  29.098427242000003     0.23408827099999996     29.337979312          340989736      47891143640
HEAD       edit                         True      100       8.765827164000001    0.0                  46.39463196900002      0.664080325             47.064813553          170987672      72973752608
upstream   getDefinition                True      100       10.798571425         0.0                  6.898966000000001e-2   2.2571604999999998e-2   9.5447319e-2          321969944      6118569104
HEAD       getDefinition                True      100       8.499385043          0.0                  4.851087600000003e-2   0.4307149750000001      0.48274966100000005   165442552      2706061416
upstream   hover after edit             True      100       10.318104219         0.0                  0.7115485499999998     31.467032214999996      32.184334215          333374144      55035838624
HEAD       hover after edit             True      100       8.361385027          0.0                  1.2198098039999996     84.45822513600004       85.685427505          179491704      135914590808
upstream   completions after edit       True      100       10.302635245000001   0.0                  7.610899137999996      24.910305101000002      32.535861899000004    340848736      69501060536
HEAD       completions after edit       True      100       8.220090383          0.0                  7.405353463999998      23.378394674            30.794549705          179435344      63398596304
upstream   code actions                 True      100       10.325744400000001   0.851846659          0.8341233790000003     4.885311700000002e-2    0.889470304           366486040      8431368256
HEAD       code actions                 True      100       8.507512788          1.0165283840000001   0.7613531869999995     0.27953688799999976     1.0470103080000002    226085272      5265320640
upstream   code actions after edit      True      100       9.138971603          0.0                  76.26359766300003      4.0910078e-2            76.309519799          388376368      126941275680
HEAD       code actions after edit      True      100       8.649876863000001    0.0                  72.44655661399999      0.557798062             73.010355753          251039568      118120315960
upstream   documentSymbols after edit   True      100       9.113513695          0.0                  0.4362658070000001     0.5181674019999999      0.960071666           329304592      8886547368
HEAD       documentSymbols after edit   True      100       8.690721853000001    0.0                  0.4860631049999999     1.1957221729999992      1.692200884           170967936      6074347248
```

`GetHieAsts` in kick, before `GenerateCore`, comment out `setPriority` calls:

```
version    name                         success   samples   startup              setup                userTime               delayedTime             totalTime             maxResidency   allocatedBytes
upstream   hover                        True      100       10.315408576000001   0.0                  9.831366799999999e-2   3.699541600000002e-2    0.14012470300000002   321691896      6134062608
HEAD       hover                        True      100       8.548917478          0.0                  0.456858668            3.445035799999999e-2    0.495167032           165792608      2727530184
upstream   edit                         True      100       10.240406717         0.0                  27.38318153500001      4.8417247000000024e-2   27.436849016          339632312      47863846952
HEAD       edit                         True      100       8.700604122          0.0                  43.483930777999994     0.6516491850000004      44.141354883000005    170946672      72916590888
upstream   getDefinition                True      100       10.202807556         0.0                  6.765188200000002e-2   2.2063011999999996e-2   9.3294734e-2          319945768      6113500648
HEAD       getDefinition                True      100       8.38729588           0.0                  4.833235399999999e-2   0.4306541579999998      0.48267244800000003   165547208      2705492312
upstream   hover after edit             True      100       10.404336751         0.0                  0.7007416579999999     32.14477865400001       32.851825981000005    334721232      55026628240
HEAD       hover after edit             True      100       7.708667566000001    0.0                  1.1048736559999999     78.31620816100002       79.428171477          179500912      135897433384
upstream   completions after edit       True      100       9.478778158          0.0                  7.102560964000002      21.815204228000002      28.925760278000002    341006840      69536902104
HEAD       completions after edit       True      100       7.683384281          0.0                  6.641168677000002      19.570225506999996      26.219458735          179575336      63408945720
upstream   code actions                 True      100       9.264510503          0.7659861090000001   0.6832428040000005     4.350983400000002e-2    0.732095135           366920864      8435983512
HEAD       code actions                 True      100       7.442306086          0.9108634440000001   0.7330711350000001     0.27202903699999986     1.011021403           226070608      5268403224
upstream   code actions after edit      True      100       9.253195393          0.0                  65.390753695           4.043268800000001e-2    65.43549303900001     388405832      126983271912
HEAD       code actions after edit      True      100       7.6850170890000005   0.0                  61.956456467000024     0.4275093000000002      62.388961800000004    258649048      118182045320
upstream   documentSymbols after edit   True      100       9.827377309000001    0.0                  0.4307532709999999     0.5203566599999999      0.958181762           329598192      8868130472
HEAD       documentSymbols after edit   True      100       7.656848248          0.0                  0.4194009209999999     1.0198141990000005      1.446465452           171111800      6068629840
```

**Comment by pepeiborra** [comment]
Shake profiling can be really handy in this situation. `ghcide-bench` can produce shake profiles, you could run the "hover after edit" experiment manually (just 1 repetition) and take a look.

**Comment by pepeiborra** [comment]
Oh, and make sure to try the `parallel` Shake combinator too

**Comment by wz1000** [comment]
The issue was that `GetDocMap` was depending on `GetModIface` which now compiles to object code(when needed). I've replaced this dependency with `Typecheck`, which has brought the results in line with expectations.

Here are the latest benchmarks:

```
version    name                         success   samples   startup              setup                userTime               delayedTime             totalTime              maxResidency   allocatedBytes
upstream   hover                        True      100       9.525369424          0.0                  7.695075600000002e-2   2.8028138000000008e-2   0.108348015            320639648      6146675296
HEAD       hover                        True      100       7.822766430000001    0.0                  6.384978300000002e-2   0.39750964300000025     0.464925079            166814104      2733423360
upstream   edit                         True      100       9.529022539000001    0.0                  24.534584883999997     5.038174800000002e-2    24.590158242           339000248      47849620536
HEAD       edit                         True      100       8.158981373000001    0.0                  37.29519746100001      0.605533363             37.905992968           173619920      71951988744
upstream   getDefinition                True      100       9.365484007000001    0.0                  6.2920481e-2           2.211287900000001e-2    8.876869100000001e-2   320874872      6115448248
HEAD       getDefinition                True      100       7.930902361          0.0                  4.6855734e-2           0.4148883               0.46524783200000003    167239112      2721402192
upstream   hover after edit             True      100       9.446113146          0.0                  0.6532941850000001     27.001553357            27.660723441000002     334357936      55014787232
HEAD       hover after edit             True      100       7.92871325           0.0                  0.4522224900000002     25.155122363000004      25.614047483           172023904      50524983080
upstream   completions after edit       True      100       9.375854870000001    0.0                  6.8314683400000025     20.961198858000003      27.800385367           341183904      69570385104
HEAD       completions after edit       True      100       7.96633173           0.0                  6.704236345000001      19.798218553            26.509848077           180179032      65871861104
upstream   code actions                 True      100       9.350566878          0.7508449610000001   0.8733336400000006     5.1729254999999974e-2   0.937164799            367226552      8430970656
HEAD       code actions                 True      100       7.80757424           0.9371481190000001   0.7492810789999998     0.27491339899999984     1.029853523            228729064      5249153240
upstream   code actions after edit      True      100       9.328880766000001    0.0                  65.01292108999999      3.9606818999999995e-2   65.057035825           388665832      126973781944
HEAD       code actions after edit      True      100       7.8775488220000005   0.0                  62.76174656099999      0.4431282919999999      63.211080766           253668888      119114938624
upstream   documentSymbols after edit   True      100       9.277836209          0.0                  0.41479268700000016    0.5277861249999999      0.948231236            329976464      8881892600
HEAD       documentSymbols after edit   True      100       8.01169685           0.0                  0.4289648420000001     1.0413405729999998      1.4775374350000001     173747176      6276714232
```

I believe most of the time regressions are attributable to desugaring.

I have to say, it is awesome that we can detect and diagnose such problems using the benchmark tools. Thank you @pepeiborra!

File: src/Development/IDE/Core/RuleTypes.hs [hunk 14]
```diff
@@ -52,49 +54,68 @@ type instance RuleResult GetDependencies = TransitiveDependencies
...
+type instance RuleResult GetImportMap = ImportMap
+newtype ImportMap = ImportMap
+  { importMap :: M.Map ModuleName NormalizedFilePath -- ^ Where are the modules imported by this file located?
+  } deriving stock Show
+    deriving newtype NFData
+
 -- | Contains the typechecked module and the OrigNameCache entry for
 -- that module.
 data TcModuleResult = TcModuleResult
-    { tmrModule     :: TypecheckedModule
```
Comment (pepeiborra) [inline src/Development/IDE/Core/RuleTypes.hs:65]: Is there any way to recover `tmrModule` from the new fields in `TcModuleResult`?  It's used by 3 plugins in HLS so recovering it would smooth things downstream.

If not, consider adding a helper in the `Rules` module and export it from `Development.IDE`:
```
 getTypecheckedModule :: NormalizedFilePath -> Action (Maybe TypecheckedModule)
```

**Comment by pepeiborra** [comment]
> The issue was that `GetDocMap` was depending on `GetModIface` which now compiles to object code(when needed). I've replaced this dependency with `Typecheck`, which has brought the results in line with expectations.

That makes sense but it is very counter intuitive: `GetModIface` becomes more expensive than `Typecheck` in some cases. Please document this clearly.

It is a bit confusing, so I'm wondering whether we should introduce a new rule `GetLeanModIface`. Take for instance the Retrie plugin, where I call `GetModIface` in order to retrieve the `mi_fixities` field for every file being refactored. What should I do now? 

* Call `Typecheck` instead: bad idea for non FOIs
* Stick to `GetModIface`: perf regression in TH cases
* (hypothetically) Call `GetLeanModIface`: no perf regression and works for all files

File: src/Development/IDE/Core/RuleTypes.hs (hunk 14 above)
Comment (wz1000) [reply src/Development/IDE/Core/RuleTypes.hs:65]: No, a `TypecheckedModule` contains `ModDetails`, which 

I don't think anything in hls needs `ModDetails`, which was not being generated properly for modules that used TH/need to be compiled, since it requires desugared source to properly generate (see my comment about `tidyProgram`) above.

The rest of the fields in a `TypecheckedModule` are available in `TcModuleResult`, so porting shouldn't be too much of an issue.

**Comment by wz1000** [comment]
> It is a bit confusing, so I'm wondering whether we should introduce a new rule `GetLeanModIface`. Take for instance the Retrie plugin, where I call `GetModIface` in order to retrieve the `mi_fixities` field for every file being refactored. What should I do now?

I don't think this will be too much of an issue. It was only showing up as a problem in this case *because* we were calling it on a FOI (which changes often, so we don't have up to date object code). For non-FOIs, we will usually have up to date object code thanks to `typecheckParents` and `InitialLoad`. Since retrie isn't meant for continuous, interactive use (like hover), it should be OK to generate object code when we need to do a refactor.

**Comment by maralorn** [comment]
Thank you so much! This is great!
