### PR TITLE
Fix bug in exports map

### LINKED ISSUE #771: Space leak
A space leak was introduced in 09aa8e5f4b4ba26981fdb34afa550ec4eaeaeb4b. 

In the benchmarks below (done in a laptop, so time measurements are not reliable), `upstream7` points to said commit and `upstream8` points to the preceding one:

image

image

```
version     name                         success   samples   startup              setup                experiment            maxResidency
v0.3.0      hover                        True      100       12.231305626000001   0.0                  0.169445642           189MB
v0.3.0      edit                         True      100       12.78367425          0.0                  30.763987565          194MB
v0.3.0      getDefinition                True      100       11.893008019000002   0.0                  0.34390903300000003   188MB
v0.3.0      hover after edit             True      100       12.628965528         0.0                  0.874594706           198MB
v0.3.0      completions after edit       True      100       11.845721274         0.0                  4.793574074           203MB
v0.3.0      code actions                 True      100       11.654060569         0.6809615240000001   0.494493726           226MB
v0.3.0      code actions after edit      True      100       12.053217982000001   0.0                  19.507116176          231MB
v0.3.0      documentSymbols after edit   True      100       11.521441841000001   0.0                  1.9631764980000002    194MB
upstream8   hover                        True      100       9.919293366          0.0                  6.1624570180000005    178MB
upstream8   edit                         True      100       9.558010323000001    0.0                  30.27085225           200MB
upstream8   getDefinition                True      100       10.069463497000001   0.0                  7.071019891000001     179MB
upstream8   hover after edit             True      100       10.523055218000001   0.0                  7.636128139           198MB
upstream8   completions after edit       True      100       10.279496557         0.0                  11.479386952          208MB
upstream8   code actions                 True      100       10.391476541000001   1.3295288010000001   6.9592471730000005    227MB
upstream8   code actions after edit      True      100       10.325661813         0.0                  25.534171453000003    229MB
upstream8   documentSymbols after edit   True      100       9.884665435          0.0                  2.010996705           182MB
upstream7   hover                        True      100       9.221848094          0.0                  9.094360360000001     577MB
upstream7   edit                         True      100       9.369224348000001    0.0                  30.425357468          597MB
upstream7   getDefinition                True      100       9.377514589          0.0                  8.94990134            577MB
upstream7   hover after edit             True      100       9.516551374          0.0                  10.044366913000001    597MB
upstream7   completions after edit       True      100       11.22539952          0.0                  14.46784101           607MB
upstream7   code actions                 True      100       10.891388644000001   1.461806607          10.342958822          575MB
upstream7   code actions after edit      True      100       9.484472901          0.0                  28.200788533          576MB
upstream7   documentSymbols after edit   True      100       9.451419864          0.0                  1.926963801           181MB
```

### PR DESCRIPTION
**Pull request by pepeiborra**
It was appending lists of identifiers without pruning duplicates

Fixes #771 

image

```
pepeiborra@pepeiborra-mbp w1 % column -t -s , bench-hist/results.csv
version    name                         success   samples   startup              setup                experiment           maxResidency
upstream   hover                        True      100       10.822233228         0.0                  2.436788999          582MB
upstream   edit                         True      100       9.478771113          0.0                  35.664150921         600MB
upstream   getDefinition                True      100       9.838020262          0.0                  2.5956575830000004   587MB
upstream   hover after edit             True      100       11.241869796000001   0.0                  5.150880557000001    566MB
upstream   completions after edit       True      100       10.113484234000001   0.0                  10.774867441000001   472MB
upstream   code actions                 True      100       10.635542301000001   4.162216031          0.527846514          552MB
upstream   code actions after edit      True      100       10.098725835         0.0                  25.293623039         545MB
upstream   documentSymbols after edit   True      100       16.169403093         0.0                  5.21765379           276MB
HEAD       hover                        True      100       9.445237065          0.0                  1.800860836          223MB
HEAD       edit                         True      100       9.710649867          0.0                  33.898333637         204MB
HEAD       getDefinition                True      100       9.380904548          0.0                  1.9576130440000001   222MB
HEAD       hover after edit             True      100       9.768509064          0.0                  4.9657159680000005   191MB
HEAD       completions after edit       True      100       9.609953897          0.0                  9.033533009000001    223MB
HEAD       code actions                 True      100       9.570470244000001    2.6726778230000003   1.4915889900000001   238MB
HEAD       code actions after edit      True      100       9.359972777000001    0.0                  21.629622857         237MB
HEAD       documentSymbols after edit   True      100       9.768980766          0.0                  4.321581539          182MB
```

### CODE REVIEW

File: session-loader/Development/IDE/Session.hs [hunk 1]
```diff
@@ -312,7 +313,7 @@ loadSession dir = do
             -- update xports map
             extras <- getShakeExtras
             let !exportsMap' = createExportsMap $ mapMaybe (fmap hirModIface) modIfaces
-            liftIO $ modifyVar_ (exportsMap extras) $ return . (exportsMap' <>)
+            liftIO $ modifyVar_ (exportsMap extras) $ evaluate . (exportsMap' <>)
```
Comment (ndmitchell) [inline session-loader/Development/IDE/Session.hs:316]: Definitely! We should probably add an HLint rule for this - or wrap modifyVar_ into modifyVar_' and only use those.

File: src/Development/IDE/Types/Exports.hs [hunk 2]
```diff
@@ -16,8 +18,17 @@ import Name
 import FieldLabel (flSelector)
 import qualified Data.HashMap.Strict as Map
 import GhcPlugins (IfaceExport)
+import Data.HashSet (HashSet)
+import qualified Data.HashSet as Set
+import Data.Bifunctor (Bifunctor(second))
```
Comment (ndmitchell) [inline src/Development/IDE/Types/Exports.hs:23]: I would usually use Data.Tuple.Extra.second here

**Review by ndmitchell — APPROVED** [review]

File: session-loader/Development/IDE/Session.hs (hunk 1 above)
Comment (pepeiborra) [reply session-loader/Development/IDE/Session.hs:316]: An hlint rule would be great

File: src/Development/IDE/Types/Exports.hs (hunk 2 above)
Comment (pepeiborra) [reply src/Development/IDE/Types/Exports.hs:23]: I'm ambivalent. Leaving as it is to skip 3h waiting for CI
