### PR TITLE
Import paths are relative to cradle

### LINKED ISSUE #780: Weird errors with imports in subcomponents
HEAD is broken in projects with multiple components like Haskell-language-server, where the ghcide source files are displaying diagnostics like the ones below:

```
Could not load module ‘Development.IDE.Core.OfInterest’
It is a member of the package ‘ghcide-0.3.0-inplace’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haddock-library-1.8.0-LPtC0wpeOzq72VzK3YVOos haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.7.1-c8704cee network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcide-0.2.0-inplace’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-EUUr586pOV5DvoTWhOg36G extra-1.7.4-KG0FyIWrVg73wbGWfgXYSy fuzzy-0.1.0.0-HLBS75LN3CdCeWDlMw7l0W ghc-check-0.5.0.1-EHkeuqUD2wJI6tJIJnbi9Q haddock-library-1.8.0-82mIVJ0TbJjABb3m79I1kb haskell-lsp-0.22.0.0-HG8sehyRYeSGZ4thlOum3Z haskell-lsp-types-0.22.0.0-6UrmcyFZoh2GWkhAQxI3cR h-bs-0.6.1-5030455e network-uri-2.6.3.0-1u5F1NB0vTTI5ASEErWNMc prettyprinter-1.6.2-60XXY2skoMwKBU4ttvgd14 prettyprinter-ansi-terminal-1.1.1.2-EC3jQYHw9Q7EKZlsKIwJlq safe-exceptions-0.1.7.0-LdG7YK1RMkSIt2CETGGSCg shake-0.19.1-9t93in5US46FSh4fNQCGA
It is a member of the package ‘ghcd-0.3.0-f5ab6e00’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-d4e3c80d’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-cd567e16’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-ca0be28c’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-ba6eafd6’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-b0506349’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-8fc4c194’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-8eae4672’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-815e2248’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-1e6a6472 network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-72b487b0’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-6005e462’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-50209fed’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-3b2c0420’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-1e6a6472 network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-2b6cccec’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-29a4ae1f’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.3.0-21c53905’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
It is a member of the package ‘ghcd-0.2.0-2e11dee1’
which is unusable due to missing dependencies:
  aeson-1.4.7.1-4sEiPjP5WcBK1Q1UclmkRE extra-1.7.5-2daYrc20nozFQitEFqq4Ow fuzzy-0.1.0.0-3QNypVfdauf69uAwn63kXW ghc-check-0.5.0.1-1NFYFg7JT1W2RrciFtTFSJ haskell-lsp-0.22.0.0-FCmA8S0bwH85PdCM5Rtpfx haskell-lsp-types-0.22.0.0-DrPR7wyRnwy18jEV5iGaHA h-bs-0.6.1-215754bc network-uri-2.6.3.0-D4kkitky4VV3K9H2VAW47C prettyprinter-1.6.2-7xiHsoNQ8yX5VYawz36ha9 prettyprinter-ansi-terminal-1.1.2-6JblOfb3ycMLtowhsKf3ZH safe-exceptions-0.1.7.0-HKtPBPhj20GKG5B8MpwmL9 shake-0.19.1-86XfWjXkHUSERkTkeZ7DVQ
```

### PR DESCRIPTION
**Pull request by pepeiborra**
I noticed ghcide HEAD was broken on the ghcide submodule of the haskell-language-server repo, after the recent changes to import paths. Hopefully this fixes the issue

Fixes #780

### CODE REVIEW

File: session-loader/Development/IDE/Session.hs [hunk 1]
```diff
@@ -299,14 +298,15 @@ loadSession dir = do
...
         return (fmap snd as, wait as)
-      unless (null cs) $
+      unless (null cs) $ do
+        cfps' <- liftIO $ filterM (IO.doesFileExist . fromNormalizedFilePath) cs
+        liftIO $ modifyVar_ knownFilesVar $ traverseHashed $ \known -> do
+            evaluate $ HashSet.union known (HashSet.fromList cfps')
         -- Typecheck all files in the project on startup
         void $ shakeEnqueue extras $ mkDelayedAction "InitialLoad" Debug $ void $ do
-          cfps' <- liftIO $ filterM (IO.doesFileExist . fromNormalizedFilePath) cs
           -- populate the knownFilesVar with all the
```
Comment (wz1000) [inline session-loader/Development/IDE/Session.hs:307]: Comment is out of place now

**Review by wz1000 — APPROVED** [review]

**Comment by pepeiborra** [comment]
Once again I had to special case the implicit cradle...

**Comment by pepeiborra** [comment]
@wz1000 check that my change to not filter by `doesFileExist` when adding to known files doesn't break anything

**Comment by wz1000** [comment]
Why remove the check that the files exist? The file paths are still coming from the same source as far as I can tell, last I remember they were generated by something like a cartesian product of import paths and module names.

**Comment by wz1000** [comment]
I think the files eventually go here, so this is not correct: https://github.com/haskell/ghcide/blob/master/src/Development/IDE/Core/Rules.hs#L381

**Comment by jneira** [comment]
> 
> 
> Once again I had to special case the implicit cradle...

would that be needed after #782?

**Comment by pepeiborra** [comment]
> Why remove the check that the files exist? The file paths are still coming from the same source as far as I can tell, last I remember they were generated by something like a cartesian product of import paths and module names.

I'm removing the check that the files exist (when extending the set of known files) because otherwise ghcide doesn't pick up new modules created after updating the cradle. 

Is the Cartesian product logic in hie-bios or in ghc?

**Comment by pepeiborra** [comment]
> I think the files eventually go here, so this is not correct: https://github.com/haskell/ghcide/blob/master/src/Development/IDE/Core/Rules.hs#L374

this doesn't seem related

**Comment by pepeiborra** [comment]
> > Once again I had to special case the implicit cradle...
> 
> would that be needed after #782?

I don't know, it depends on what is changed in #782.

**Comment by wz1000** [comment]
> > I think the files eventually go here, so this is not correct: https://github.com/haskell/ghcide/blob/master/src/Development/IDE/Core/Rules.hs#L374
> 
> this doesn't seem related

It is. We call `use_ GetModSummaryWithoutTimestamps` on each file name put into the known files list, which will fail every time if any of those files don't exist.

**Comment by wz1000** [comment]
> > Why remove the check that the files exist? The file paths are still coming from the same source as far as I can tell, last I remember they were generated by something like a cartesian product of import paths and module names.
> 
> I'm removing the check that the files exist (when extending the set of known files) because otherwise ghcide doesn't pick up new modules created after updating the cradle.
> 
> Is the Cartesian product logic in hie-bios or in ghc?

It's in `ghcide`: https://github.com/haskell/ghcide/blob/master/session-loader/Development/IDE/Session.hs#L359

**Comment by pepeiborra** [comment]
> > Is the Cartesian product logic in hie-bios or in ghc?
> 
> It's in `ghcide`: https://github.com/haskell/ghcide/blob/master/session-loader/Development/IDE/Session.hs#L359

I see your point now. I've restored the filtering and implemented an alternative solution for missing modules which preserves the old behaviour

**Comment by pepeiborra** [comment]
The problem is that we are trying to use the KnownFiles to determine what imports are part of the local project, and the KnownFiles do not have enough information for that. 

The solution is to enrich the KnownFiles to become KnownTargets, which provides a mapping from every target to a list of normalised file paths that do exist for them. The keys of the mapping are the targets and can be used to determine local imports, whereas the values of the mapping are still used to drive the module graph

**Comment by wz1000** [comment]
Won't we still end up calling `rawDependencyInformation` with a bunch of non existent files?

**Comment by pepeiborra** [comment]
> Won't we still end up calling `rawDependencyInformation` with a bunch of non existent files?

I restored the filtering, so I don't think so

File: src/Development/IDE/Core/Rules.hs [hunk 2]
```diff
@@ -314,15 +315,20 @@ getLocatedImportsRule :: Rules ()
...
-        let dflags = addRelativeImport file (moduleName $ ms_mod ms) $ hsc_dflags env
+        let dflags = hsc_dflags env
+            isImplicitCradle = isNothing $ envImportPaths env_eq
+        dflags <- return $ if isImplicitCradle
+                    then addRelativeImport file (moduleName $ ms_mod ms) dflags
+                    else dflags
         opt <- getIdeOptions
-        let getTargetExists nfp
-                | HashSet.null targets || nfp `HashSet.member` targets = getFileExists nfp
+        let getTargetExists modName nfp
```
Comment (wz1000) [inline src/Development/IDE/Core/Rules.hs:329]: Do we not need the `HashSet.null` check anymore because we update the knownTargets var sooner?

File: src/Development/IDE/Core/FileStore.hs [hunk 3]
```diff
@@ -230,7 +230,7 @@ typecheckParents state nfp = void $ shakeEnqueue (shakeExtras state) parents
 
 typecheckParentsAction :: NormalizedFilePath -> Action ()
 typecheckParentsAction nfp = do
-    fs <- useNoFile_ GetKnownFiles
+    fs <- useNoFile_ GetKnownTargets
     unless (null fs) $ do
```
Comment (wz1000) [inline src/Development/IDE/Core/FileStore.hs:234]: If `KnownTargets` is always populated here, I don't think we need this check anymore.

File: src/Development/IDE/Core/Rules.hs (hunk 2 above)
Comment (pepeiborra) [reply src/Development/IDE/Core/Rules.hs:329]: what about "bad" direct cradles?

File: src/Development/IDE/Core/FileStore.hs (hunk 3 above)
Comment (pepeiborra) [reply src/Development/IDE/Core/FileStore.hs:234]: this one can be removed indeed

**Comment by pepeiborra** [comment]
I have disabled a flaky test that was blocking this PR. Have you noticed this test failing before?

**Comment by wz1000** [comment]
Yes, I saw it for the first time yesterday. Rerunning the job fixed it.
Maybe saving ifaces exposed this? Switching the order of iface-error-1 and
iface-error-2 could be one way to tell.

**Comment by pepeiborra** [comment]
> Yes, I saw it for the first time yesterday. Rerunning the job fixed it. Maybe saving ifaces exposed this? Switching the order of iface-error-1 and iface-error-2 could be one way to tell.
> […](#)

I think it's likely related to saving faces. Could you investigate? The failure could be indicative of a real bug
